name: GitHub Actions Demo
on: [pull_request]

jobs:
  eslint:
    name: run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          command: eslint
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          package-manager: npm
          command: test:ci
